### ISSUE TITLE
Richiesta delucidazioni implementazione applicazione client-server

### ISSUE THREAD

**Issue by RobertaConti-Jarvis** [irenedg/rubrica-telefonica-uno#12]
Buongiorno professor Lezzerini,
ci sembra di ricordare che oltre alla documentazione fornita, Lei ci ha detto che l'applicazione dovesse funzionare solo lato client, in modo da consolidare gli argomenti trattati durante le ultime lezioni e che se rimaneva tempo potevamo dedicarci allo sviluppo del codice lato server.
In questo caso, abbiamo la necessità di chiederle, implementando il lato server, come la parte client, già funzionante, ne risentirebbe.
Noi avevamo pensato di duplicare il progetto lato client e far partire uno o l'altro a seconda delle necessità o in alternativa, nello stesso progetto client, commentando le parti non più necessarie con lo sviluppo del server.

**Comment by luca-lezzerini** [comment]
Ok va bene, duplicate il client

**Comment by AulicinoDiego** [comment]
risolto con Commit : 09b8284f1f908accd5c191010ffc3f967958767e
