### ISSUE TITLE
Lato server:  richiesta delucidazione relativamente alla documentazione per quanto riguarda l'entità Utente mancante

### ISSUE THREAD

**Issue by RobertaConti-Jarvis** [irenedg/rubrica-telefonica-uno#13]
Buongiorno professor Lezzerini,
a pagina 15 e 19 della documentazione da Lei fornita, osserviamo che è previsto il controllo delle credenziali di accesso all'applicazione, ma non è stata indicata nessuna entità Utente. 
Cosa dobbiamo fare?

**Comment by luca-lezzerini** [comment]
Usate credenziali fisse hardcodate (ossia sctitte nel codice) senza creare entità utente.
Usate user come username e psw come password

**Comment by AulicinoDiego** [comment]
Risolto con Commit : 3ed0cd83c3a45629291f6ffeaf3f5b4154c03fa1
