### ISSUE TITLE
Lato server: dto mancanti nella documentazione

### ISSUE THREAD

**Issue by RobertaConti-Jarvis** [irenedg/rubrica-telefonica-uno#14]
Buongiorno professor Lezzerini,
volevamo farLe presente che nella documentazione non sono riportati tutti i dto richiesti dai metodi del controller, vedi IdDto, ListaContattiDto.
Noi li abbiamo aggiunti nel package ..dto
Va bene, come stiamo procedendo?

**Comment by luca-lezzerini** [comment]
Va bene definite livoi e metteteli nel package dto

**Comment by RobertaConti-Jarvis** [comment]
Ticket risolto con la risposta del professor Lezzerini
