### ISSUE TITLE
Solo client: Malfunzionamento metodo Cerca

### ISSUE THREAD

**Issue by RobertaConti-Jarvis** [irenedg/rubrica-telefonica-uno#15]
Nel caso in cui, nel metodo cerca,  il criterio di ricerca non venga impostato e viene premuto il bottone Cerca, devono essere visualizzati tutti i contatti.

**Comment by AulicinoDiego** [comment]
risolto con commit: 09b8284f1f908accd5c191010ffc3f967958767e
