### ISSUE TITLE
Implementazione lato client applicazione client-server

### ISSUE THREAD

**Issue by RobertaConti-Jarvis** [irenedg/rubrica-telefonica-uno#16]

**Comment by AulicinoDiego** [comment]
Implementato chiamate Rest metodi(aggingi e carica-contatti) in Main-page. Commit : 09b8284f1f908accd5c191010ffc3f967958767e

**Comment by RobertaConti-Jarvis** [comment]
implementato check-login con chiamata Rest. Commit: 9f44748afbd60378fb80a438a9b4abcbb09cc56d

**Comment by irenedg** [comment]
Risolto con Commit: 7687ed0fee48fbdc48b67c27ed360b975713b357
