### ISSUE TITLE
Implementare UC Aggiungi Contatto

### ISSUE THREAD

**Issue by RobertaConti-Jarvis** [irenedg/rubrica-telefonica-uno#7]
In questo caso d'uso, l'utente aggiunge un nuovo contatto alla rubrica

**Comment by RobertaConti-Jarvis** [comment]
In questo caso d'uso, l'utente aggiunge un nuovo contatto alla rubrica

**Comment by AulicinoDiego** [comment]
Risolto con Commit : d2260551264f21fa87d70f4cb2921a8b1b23fe5d
